// ===== Customers page JS =====
const custCheckAll=document.getElementById('cust-check-all');
const custChecks=document.querySelectorAll('.cust-check');
const custBatchBar=document.getElementById('cust-batch-bar');
const custBatchCount=document.getElementById('cust-batch-count');
if(custCheckAll)custCheckAll.addEventListener('change',e=>{custChecks.forEach(c=>c.checked=e.target.checked);updateBatchBar();});
custChecks.forEach(c=>c.addEventListener('change',updateBatchBar));
function updateBatchBar(){const n=[...custChecks].filter(c=>c.checked).length;if(custBatchCount)custBatchCount.textContent=n;if(custBatchBar)custBatchBar.style.display=n>0?'flex':'none';if(custCheckAll)custCheckAll.checked=n===custChecks.length;}
function toggleFilterDropdown(btn){const dd=btn.parentElement;document.querySelectorAll('.filter-dropdown.open').forEach(d=>{if(d!==dd)d.classList.remove('open');});dd.classList.toggle('open');}
function selectFilterOption(el){const dd=el.closest('.filter-dropdown');if(!dd)return;const tr=dd.querySelector('.filter-trigger');const vs=tr.querySelector('.filter-value');dd.querySelectorAll('.filter-option').forEach(o=>o.classList.remove('active'));el.classList.add('active');if(vs)vs.textContent=el.textContent;dd.classList.remove('open');}
document.addEventListener('click',e=>{if(!e.target.closest('.filter-dropdown'))document.querySelectorAll('.filter-dropdown.open').forEach(d=>d.classList.remove('open'));});
function openModal(id){const m=document.getElementById(id);if(m)m.style.display='flex';if(id==='modal-batch-edit'||id==='modal-batch-export'){const n=[...document.querySelectorAll('.cust-check')].filter(c=>c.checked).length;const ec=document.getElementById('batch-edit-count');const xc=document.getElementById('batch-export-count');if(ec)ec.textContent=n;if(xc)xc.textContent=n;}}
function closeModal(id){const m=document.getElementById(id);if(m)m.style.display='none';}
function toggleSort(th){const key=th.dataset.sortKey;if(!key)return;const isAsc=th.classList.contains('sort-asc');document.querySelectorAll('#cust-table .th-sortable').forEach(t=>{t.classList.remove('sort-asc','sort-desc');});if(isAsc){th.classList.add('sort-desc');}else{th.classList.add('sort-asc');}}
document.querySelectorAll('.batch-field-card input[type="checkbox"]').forEach(cb=>{cb.addEventListener('change',()=>{cb.closest('.batch-field-card').classList.toggle('active',cb.checked);});});
function showBatchEditPreview(){const checked=[...document.querySelectorAll('.batch-field-card input[type="checkbox"]:checked')];if(checked.length===0){alert('请至少勾选一个要修改的字段');return;}closeModal('modal-batch-edit');alert('预览：将修改 '+document.getElementById('batch-edit-count').textContent+' 个客户的 '+checked.length+' 个字段');}
function confirmBatchEdit(){const checked=[...document.querySelectorAll('.batch-field-card input[type="checkbox"]:checked')];if(checked.length===0){alert('请至少勾选一个要修改的字段');return;}closeModal('modal-batch-edit');}
function applyColSettingsModal(){document.querySelectorAll('#modal-col-settings-grid input[type="checkbox"]').forEach(cb=>{const col=cb.dataset.col;document.querySelectorAll(`#cust-table [data-col="${col}"]`).forEach(el=>{el.style.display=cb.checked?'':'none';});});closeModal('modal-col-settings');}
function resetColSettingsModal(){const ds=['customer','industry','scale','consume','balance','usage','health','ops-manager','sales-manager'];document.querySelectorAll('#modal-col-settings-grid input[type="checkbox"]').forEach(cb=>{cb.checked=ds.includes(cb.dataset.col);});}
const kpiFilters={'all':{label:'全部客户',filters:{}},'key':{label:'重点客户',filters:{consume:'S'}},'incomplete':{label:'待完善画像',filters:{industry:'待完善'}},'mine':{label:'我的客户',filters:{'ops-manager':'张经理'}}};
function applyKpiFilter(key){document.querySelectorAll('.kpi-clickable').forEach(c=>c.classList.remove('kpi-active'));const card=document.querySelector(`[data-kpi="${key}"]`);if(card)card.classList.add('kpi-active');const badge=document.getElementById('kpi-filter-badge');const config=kpiFilters[key];if(!config)return;if(key==='all'){if(badge)badge.style.display='none';document.querySelectorAll('.filter-dropdown').forEach(dd=>{const tr=dd.querySelector('.filter-trigger');const val=tr.querySelector('.filter-value');const opts=dd.querySelectorAll('.filter-option');opts.forEach(o=>o.classList.remove('active'));if(opts[0]){opts[0].classList.add('active');if(val)val.textContent=opts[0].textContent;}});return;}if(badge){badge.style.display='inline-flex';badge.innerHTML=config.label+' <span class="badge-close" onclick="applyKpiFilter(&#39;all&#39;)">✕</span>';}Object.entries(config.filters).forEach(([fk,value])=>{const dd=document.querySelector(`[data-filter-key="${fk}"]`);if(!dd)return;const tr=dd.querySelector('.filter-trigger');const val=tr.querySelector('.filter-value');dd.querySelectorAll('.filter-option').forEach(o=>{o.classList.remove('active');if(o.dataset.value===value){o.classList.add('active');if(val)val.textContent=o.textContent;}});});}
function openPreviewDrawer(row){const drawer=document.getElementById('preview-drawer');if(!drawer)return;const name=row.querySelector('[data-col="customer"] b');const logo=row.querySelector('[data-col="customer"] .logo');const industry=row.querySelector('[data-col="industry"]');const scale=row.querySelector('[data-col="scale"]');const consume=row.querySelector('[data-col="consume"]');const balance=row.querySelector('[data-col="balance"]');const health=row.querySelector('[data-col="health"]');if(name)document.getElementById('drawer-name').textContent=name.textContent;if(logo)document.getElementById('drawer-logo').textContent=logo.textContent;const mp=[];if(industry)mp.push(industry.textContent.trim().split(' ')[0]);if(scale)mp.push('规模 '+scale.textContent);if(consume)mp.push('消费 '+consume.textContent);document.getElementById('drawer-meta').textContent=mp.join(' · ');if(balance)document.getElementById('drawer-balance').textContent=balance.textContent;if(health){const h=health.querySelector('.tag');if(h)document.getElementById('drawer-health').textContent=h.textContent;}drawer.classList.add('open');}
function closePreviewDrawer(){const drawer=document.getElementById('preview-drawer');if(drawer)drawer.classList.remove('open');}
