"""add customer groups models

Revision ID: 002
Revises: 001
Create Date: 2026-04-03

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "002"
down_revision: Union[str, None] = "001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###

    # 创建客户群组表
    op.create_table(
        "customer_groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("group_type", sa.String(length=20), nullable=False),
        sa.Column("filter_conditions", sa.JSON(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_customer_groups_created_by",
        "customer_groups",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        "idx_customer_groups_group_type",
        "customer_groups",
        ["group_type"],
        unique=False,
    )
    op.create_index(
        "idx_customer_groups_name", "customer_groups", ["name"], unique=False
    )
    op.create_index(
        "idx_group_type_created_by",
        "customer_groups",
        ["group_type", "created_by"],
        unique=False,
    )

    # 创建群组成员表
    op.create_table(
        "customer_group_members",
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["group_id"], ["customer_groups.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id", "customer_id"),
    )
    op.create_index(
        "idx_customer_group_members_customer_id",
        "customer_group_members",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        "idx_member_customer", "customer_group_members", ["customer_id"], unique=False
    )
    op.create_index(
        "idx_member_group_customer",
        "customer_group_members",
        ["group_id", "customer_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index("idx_member_group_customer", table_name="customer_group_members")
    op.drop_index("idx_member_customer", table_name="customer_group_members")
    op.drop_index(
        "idx_customer_group_members_customer_id", table_name="customer_group_members"
    )
    op.drop_table("customer_group_members")

    op.drop_index("idx_group_type_created_by", table_name="customer_groups")
    op.drop_index("idx_customer_groups_name", table_name="customer_groups")
    op.drop_index("idx_customer_groups_group_type", table_name="customer_groups")
    op.drop_index("idx_customer_groups_created_by", table_name="customer_groups")
    op.drop_table("customer_groups")
    # ### end Alembic commands ###
