"""add webhook_signatures table

Revision ID: 002
Revises: 001_initial
Create Date: 2026-04-03

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "002"
down_revision: Union[str, None] = "001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "webhook_signatures",
        sa.Column(
            "signature", sa.String(length=64), nullable=False, comment="请求签名"
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=False, comment="请求时间戳"),
        sa.Column(
            "endpoint", sa.String(length=100), nullable=False, comment="Webhook 端点"
        ),
        sa.Column("is_consumed", sa.Boolean(), nullable=True, comment="是否已使用"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhook_signatures_signature"),
        "webhook_signatures",
        ["signature"],
        unique=True,
    )
    op.create_index(
        op.f("ix_webhook_signatures_timestamp"),
        "webhook_signatures",
        ["timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_webhook_sig_timestamp",
        "webhook_signatures",
        ["signature", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_webhook_sig_timestamp", table_name="webhook_signatures")
    op.drop_index(
        op.f("ix_webhook_signatures_timestamp"), table_name="webhook_signatures"
    )
    op.drop_index(
        op.f("ix_webhook_signatures_signature"), table_name="webhook_signatures"
    )
    op.drop_table("webhook_signatures")
    # ### end Alembic commands ###
