"""add customer detail fields

Revision ID: 003
Revises: 002
Create Date: 2026-04-14

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "003"
down_revision: Union[str, None] = "002_add_customer_groups"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic. ###

    # --- customers 表新增字段 ---
    op.add_column(
        "customers", sa.Column("erp_system", sa.String(length=100), nullable=True)
    )
    op.add_column(
        "customers", sa.Column("first_payment_date", sa.Date(), nullable=True)
    )
    op.add_column("customers", sa.Column("onboarding_date", sa.Date(), nullable=True))
    op.add_column(
        "customers", sa.Column("sales_manager_id", sa.Integer(), nullable=True)
    )
    op.add_column(
        "customers",
        sa.Column(
            "cooperation_status",
            sa.String(length=50),
            nullable=True,
            server_default="active",
        ),
    )
    op.add_column(
        "customers",
        sa.Column(
            "is_settlement_enabled",
            sa.Boolean(),
            nullable=True,
            server_default=sa.text("true"),
        ),
    )
    op.add_column(
        "customers",
        sa.Column(
            "is_disabled",
            sa.Boolean(),
            nullable=True,
            server_default=sa.text("false"),
        ),
    )
    op.add_column("customers", sa.Column("notes", sa.Text(), nullable=True))

    # customers 表外键
    op.create_foreign_key(
        "fk_customers_sales_manager",
        "customers",
        "users",
        ["sales_manager_id"],
        ["id"],
    )

    # customers 表索引
    op.create_index(
        "idx_customer_sales_manager", "customers", ["sales_manager_id"], unique=False
    )
    op.create_index(
        "idx_customer_cooperation_status",
        "customers",
        ["cooperation_status"],
        unique=False,
    )
    op.create_index("idx_customer_disabled", "customers", ["is_disabled"], unique=False)

    # --- customer_profiles 表新增字段 ---
    op.add_column(
        "customer_profiles", sa.Column("monthly_avg_shots", sa.Integer(), nullable=True)
    )
    op.add_column(
        "customer_profiles",
        sa.Column("monthly_avg_shots_estimated", sa.Integer(), nullable=True),
    )
    op.add_column(
        "customer_profiles",
        sa.Column("estimated_annual_spend", sa.Numeric(12, 2), nullable=True),
    )
    op.add_column(
        "customer_profiles",
        sa.Column("actual_annual_spend_2025", sa.Numeric(12, 2), nullable=True),
    )

    # ### end Alembic commands. ###


def downgrade() -> None:
    # ### commands auto generated by Alembic. ###

    # customer_profiles 表回滚
    op.drop_column("customer_profiles", "actual_annual_spend_2025")
    op.drop_column("customer_profiles", "estimated_annual_spend")
    op.drop_column("customer_profiles", "monthly_avg_shots_estimated")
    op.drop_column("customer_profiles", "monthly_avg_shots")

    # customers 表索引回滚
    op.drop_index("idx_customer_disabled", table_name="customers")
    op.drop_index("idx_customer_cooperation_status", table_name="customers")
    op.drop_index("idx_customer_sales_manager", table_name="customers")

    # customers 表外键回滚
    op.drop_constraint("fk_customers_sales_manager", "customers", type_="foreignkey")

    # customers 表字段回滚
    op.drop_column("customers", "notes")
    op.drop_column("customers", "is_disabled")
    op.drop_column("customers", "is_settlement_enabled")
    op.drop_column("customers", "cooperation_status")
    op.drop_column("customers", "sales_manager_id")
    op.drop_column("customers", "onboarding_date")
    op.drop_column("customers", "first_payment_date")
    op.drop_column("customers", "erp_system")

    # ### end Alembic commands. ###
