"""initial_schema

Revision ID: 05c6bedcf166
Revises:
Create Date: 2026-05-07 21:33:00.885628

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "05c6bedcf166"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "industry_types",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_industry_types_name"), "industry_types", ["name"], unique=True)
    op.create_index(
        op.f("ix_industry_types_sort_order"), "industry_types", ["sort_order"], unique=False
    )
    op.create_table(
        "permissions",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("module", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "sync_task_logs",
        sa.Column("task_name", sa.String(length=100), nullable=False, comment="任务名称"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="任务状态"),
        sa.Column("total_count", sa.Integer(), nullable=True, comment="总处理数量"),
        sa.Column("success_count", sa.Integer(), nullable=True, comment="成功数量"),
        sa.Column("failed_count", sa.Integer(), nullable=True, comment="失败数量"),
        sa.Column("skipped_count", sa.Integer(), nullable=True, comment="跳过数量"),
        sa.Column("executed_at", sa.String(length=50), nullable=True, comment="执行时间"),
        sa.Column("duration_seconds", sa.Integer(), nullable=True, comment="执行耗时 (秒)"),
        sa.Column("error_message", sa.Text(), nullable=True, comment="错误信息"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sync_task_logs_task_name"), "sync_task_logs", ["task_name"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("real_name", sa.String(length=50), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "webhook_signatures",
        sa.Column("signature", sa.String(length=64), nullable=False, comment="请求签名"),
        sa.Column("timestamp", sa.DateTime(), nullable=False, comment="请求时间戳"),
        sa.Column("endpoint", sa.String(length=100), nullable=False, comment="Webhook 端点"),
        sa.Column("is_consumed", sa.Boolean(), nullable=True, comment="是否已使用"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_webhook_sig_timestamp", "webhook_signatures", ["signature", "timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_signatures_signature"), "webhook_signatures", ["signature"], unique=True
    )
    op.create_index(
        op.f("ix_webhook_signatures_timestamp"), "webhook_signatures", ["timestamp"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("module", sa.String(length=50), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=True),
        sa.Column("record_type", sa.String(length=50), nullable=True),
        sa.Column("changes", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column(
            "operation_type",
            sa.String(length=20),
            nullable=True,
            comment="操作类型: standard/batch/relation/sensitive",
        ),
        sa.Column(
            "extra_metadata", sa.JSON(), nullable=True, comment="扩展元数据: 批量统计、关系ID列表等"
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "customers",
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("account_type", sa.String(length=50), nullable=True),
        sa.Column("price_policy", sa.String(length=50), nullable=True),
        sa.Column("manager_id", sa.Integer(), nullable=True),
        sa.Column("settlement_cycle", sa.String(length=20), nullable=True),
        sa.Column("settlement_type", sa.String(length=20), nullable=True),
        sa.Column("is_key_customer", sa.Boolean(), nullable=True),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("erp_system", sa.String(length=100), nullable=True),
        sa.Column("first_payment_date", sa.Date(), nullable=True),
        sa.Column("onboarding_date", sa.Date(), nullable=True),
        sa.Column("sales_manager_id", sa.Integer(), nullable=True),
        sa.Column("cooperation_status", sa.String(length=50), nullable=True),
        sa.Column("is_settlement_enabled", sa.Boolean(), nullable=True),
        sa.Column("is_disabled", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["manager_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sales_manager_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_customer_cooperation_status", "customers", ["cooperation_status"], unique=False
    )
    op.create_index("idx_customer_disabled", "customers", ["is_disabled"], unique=False)
    op.create_index("idx_customer_sales_manager", "customers", ["sales_manager_id"], unique=False)
    op.create_index(op.f("ix_customers_account_type"), "customers", ["account_type"], unique=False)
    op.create_index(op.f("ix_customers_company_id"), "customers", ["company_id"], unique=True)
    op.create_index(
        op.f("ix_customers_cooperation_status"), "customers", ["cooperation_status"], unique=False
    )
    op.create_index(op.f("ix_customers_email"), "customers", ["email"], unique=False)
    op.create_index(op.f("ix_customers_is_disabled"), "customers", ["is_disabled"], unique=False)
    op.create_index(
        op.f("ix_customers_is_key_customer"), "customers", ["is_key_customer"], unique=False
    )
    op.create_index(op.f("ix_customers_manager_id"), "customers", ["manager_id"], unique=False)
    op.create_index(op.f("ix_customers_name"), "customers", ["name"], unique=False)
    op.create_index(
        op.f("ix_customers_sales_manager_id"), "customers", ["sales_manager_id"], unique=False
    )
    op.create_index(
        op.f("ix_customers_settlement_type"), "customers", ["settlement_type"], unique=False
    )
    op.create_table(
        "files",
        sa.Column("filename", sa.String(length=255), nullable=False, comment="原始文件名"),
        sa.Column(
            "stored_filename", sa.String(length=255), nullable=False, comment="存储文件名（随机）"
        ),
        sa.Column("file_path", sa.String(length=500), nullable=False, comment="文件相对路径"),
        sa.Column("file_size", sa.BigInteger(), nullable=False, comment="文件大小（字节）"),
        sa.Column("file_type", sa.String(length=100), nullable=False, comment="文件 MIME 类型"),
        sa.Column("uploaded_by", sa.Integer(), nullable=False, comment="上传人 ID"),
        sa.Column(
            "file_hash",
            sa.String(length=64),
            nullable=True,
            comment="文件 SHA256 哈希值（用于去重）",
        ),
        sa.Column(
            "business_type",
            sa.String(length=50),
            nullable=True,
            comment="业务类型：customer_import/profile_image/other",
        ),
        sa.Column("business_id", sa.Integer(), nullable=True, comment="关联业务 ID"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("stored_filename"),
    )
    op.create_index(op.f("ix_files_file_hash"), "files", ["file_hash"], unique=False)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )
    op.create_table(
        "tags",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "type", name="uq_tags_name_type"),
    )
    op.create_index("idx_tag_type_category", "tags", ["type", "category"], unique=False)
    op.create_index(op.f("ix_tags_category"), "tags", ["category"], unique=False)
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=False)
    op.create_index(op.f("ix_tags_type"), "tags", ["type"], unique=False)
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    op.create_table(
        "customer_balances",
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("total_amount", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("real_amount", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("bonus_amount", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("used_total", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("used_real", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("used_bonus", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("customer_id"),
    )
    op.create_table(
        "customer_profiles",
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("scale_level", sa.String(length=50), nullable=True),
        sa.Column("consume_level", sa.String(length=50), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("is_real_estate", sa.Boolean(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("monthly_avg_shots", sa.Integer(), nullable=True),
        sa.Column("monthly_avg_shots_estimated", sa.Integer(), nullable=True),
        sa.Column("estimated_annual_spend", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("actual_annual_spend_2025", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("customer_id"),
    )
    op.create_table(
        "customer_tags",
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("customer_id", "tag_id", "id"),
    )
    op.create_table(
        "daily_usage",
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column("device_type", sa.String(length=20), nullable=False),
        sa.Column("layer_type", sa.String(length=20), nullable=True),
        sa.Column("quantity", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_daily_usage_customer_date", "daily_usage", ["customer_id", "usage_date"], unique=False
    )
    op.create_index(
        "idx_daily_usage_customer_device",
        "daily_usage",
        ["customer_id", "device_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_usage_customer_id"), "daily_usage", ["customer_id"], unique=False
    )
    op.create_index(op.f("ix_daily_usage_usage_date"), "daily_usage", ["usage_date"], unique=False)
    op.create_table(
        "invoices",
        sa.Column("invoice_no", sa.String(length=50), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("total_amount", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column("discount_amount", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("discount_reason", sa.Text(), nullable=True),
        sa.Column("discount_attachment", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("approver_id", sa.Integer(), nullable=True),
        sa.Column("approved_at", sa.String(length=50), nullable=True),
        sa.Column("customer_confirmed_at", sa.String(length=50), nullable=True),
        sa.Column("payment_proof", sa.String(length=255), nullable=True),
        sa.Column("paid_at", sa.String(length=50), nullable=True),
        sa.Column("completed_at", sa.String(length=50), nullable=True),
        sa.Column("cancelled_at", sa.String(length=50), nullable=True),
        sa.Column("is_auto_generated", sa.Boolean(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["approver_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_invoice_customer_period",
        "invoices",
        ["customer_id", "period_start", "period_end"],
        unique=False,
    )
    op.create_index(
        "idx_invoice_status_period", "invoices", ["status", "period_start"], unique=False
    )
    op.create_index(op.f("ix_invoices_customer_id"), "invoices", ["customer_id"], unique=False)
    op.create_index(op.f("ix_invoices_invoice_no"), "invoices", ["invoice_no"], unique=True)
    op.create_index(op.f("ix_invoices_period_end"), "invoices", ["period_end"], unique=False)
    op.create_index(op.f("ix_invoices_period_start"), "invoices", ["period_start"], unique=False)
    op.create_index(op.f("ix_invoices_status"), "invoices", ["status"], unique=False)
    op.create_table(
        "pricing_rules",
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("device_type", sa.String(length=20), nullable=False),
        sa.Column("layer_type", sa.String(length=20), nullable=True),
        sa.Column("pricing_type", sa.String(length=20), nullable=False),
        sa.Column("unit_price", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("tiers", sa.JSON(), nullable=True),
        sa.Column("package_type", sa.String(length=20), nullable=True),
        sa.Column("package_limits", sa.JSON(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pricing_rules_customer_id"), "pricing_rules", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_pricing_rules_effective_date"), "pricing_rules", ["effective_date"], unique=False
    )
    op.create_table(
        "recharge_records",
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("real_amount", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column("bonus_amount", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("operator_id", sa.Integer(), nullable=True),
        sa.Column("payment_proof", sa.String(length=255), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recharge_records_customer_id"), "recharge_records", ["customer_id"], unique=False
    )
    op.create_table(
        "consumption_records",
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("invoice_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column("bonus_used", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("real_used", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("balance_after", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consumption_records_customer_id"),
        "consumption_records",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumption_records_invoice_id"),
        "consumption_records",
        ["invoice_id"],
        unique=False,
    )
    op.create_table(
        "invoice_items",
        sa.Column("invoice_id", sa.Integer(), nullable=True),
        sa.Column("device_type", sa.String(length=20), nullable=False),
        sa.Column("layer_type", sa.String(length=20), nullable=True),
        sa.Column("quantity", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("unit_price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("pricing_rule_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["pricing_rule_id"],
            ["pricing_rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invoice_items_invoice_id"), "invoice_items", ["invoice_id"], unique=False
    )
    op.create_table(
        "profile_tags",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["profile_id"], ["customer_profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("profile_id", "tag_id", "id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("profile_tags")
    op.drop_index(op.f("ix_invoice_items_invoice_id"), table_name="invoice_items")
    op.drop_table("invoice_items")
    op.drop_index(op.f("ix_consumption_records_invoice_id"), table_name="consumption_records")
    op.drop_index(op.f("ix_consumption_records_customer_id"), table_name="consumption_records")
    op.drop_table("consumption_records")
    op.drop_index(op.f("ix_recharge_records_customer_id"), table_name="recharge_records")
    op.drop_table("recharge_records")
    op.drop_index(op.f("ix_pricing_rules_effective_date"), table_name="pricing_rules")
    op.drop_index(op.f("ix_pricing_rules_customer_id"), table_name="pricing_rules")
    op.drop_table("pricing_rules")
    op.drop_index(op.f("ix_invoices_status"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_period_start"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_period_end"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_invoice_no"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_customer_id"), table_name="invoices")
    op.drop_index("idx_invoice_status_period", table_name="invoices")
    op.drop_index("idx_invoice_customer_period", table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_daily_usage_usage_date"), table_name="daily_usage")
    op.drop_index(op.f("ix_daily_usage_customer_id"), table_name="daily_usage")
    op.drop_index("idx_daily_usage_customer_device", table_name="daily_usage")
    op.drop_index("idx_daily_usage_customer_date", table_name="daily_usage")
    op.drop_table("daily_usage")
    op.drop_table("customer_tags")
    op.drop_table("customer_profiles")
    op.drop_table("customer_balances")
    op.drop_table("user_roles")
    op.drop_index(op.f("ix_tags_type"), table_name="tags")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_index(op.f("ix_tags_category"), table_name="tags")
    op.drop_index("idx_tag_type_category", table_name="tags")
    op.drop_table("tags")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_files_file_hash"), table_name="files")
    op.drop_table("files")
    op.drop_index(op.f("ix_customers_settlement_type"), table_name="customers")
    op.drop_index(op.f("ix_customers_sales_manager_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_name"), table_name="customers")
    op.drop_index(op.f("ix_customers_manager_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_is_key_customer"), table_name="customers")
    op.drop_index(op.f("ix_customers_is_disabled"), table_name="customers")
    op.drop_index(op.f("ix_customers_email"), table_name="customers")
    op.drop_index(op.f("ix_customers_cooperation_status"), table_name="customers")
    op.drop_index(op.f("ix_customers_company_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_account_type"), table_name="customers")
    op.drop_index("idx_customer_sales_manager", table_name="customers")
    op.drop_index("idx_customer_disabled", table_name="customers")
    op.drop_index("idx_customer_cooperation_status", table_name="customers")
    op.drop_table("customers")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_webhook_signatures_timestamp"), table_name="webhook_signatures")
    op.drop_index(op.f("ix_webhook_signatures_signature"), table_name="webhook_signatures")
    op.drop_index("idx_webhook_sig_timestamp", table_name="webhook_signatures")
    op.drop_table("webhook_signatures")
    op.drop_table("users")
    op.drop_index(op.f("ix_sync_task_logs_task_name"), table_name="sync_task_logs")
    op.drop_table("sync_task_logs")
    op.drop_table("roles")
    op.drop_table("permissions")
    op.drop_index(op.f("ix_industry_types_sort_order"), table_name="industry_types")
    op.drop_index(op.f("ix_industry_types_name"), table_name="industry_types")
    op.drop_table("industry_types")
    # ### end Alembic commands ###
