"""Add daily_orders and daily_consumption tables

Revision ID: 41b931a886e0
Revises: b2c3d4e5f6g7
Create Date: 2026-06-14 01:11:29.908741

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

revision: str = "41b931a886e0"
down_revision: Union[str, None] = "b2c3d4e5f6g7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_orders",
        sa.Column(
            "order_code", sa.String(length=50), nullable=False, comment="订单 ID（外部系统）"
        ),
        sa.Column("custom_code", sa.String(length=50), nullable=True, comment="房源编号"),
        sa.Column("nest_id", sa.String(length=50), nullable=True, comment="模型编号"),
        sa.Column("company_name", sa.String(length=200), nullable=True, comment="公司名称"),
        sa.Column("group_type", sa.String(length=50), nullable=True, comment="客户 ID（外部系统）"),
        sa.Column("customer_id", sa.Integer(), nullable=True, comment="系统客户 ID"),
        sa.Column("create_date", sa.Date(), nullable=False, comment="订单创建时间"),
        sa.Column("floor_count", sa.Integer(), nullable=True, comment="楼层数"),
        sa.Column("device_type", sa.String(length=10), nullable=True, comment="设备类型（X/N/L）"),
        sa.Column("sync_date", sa.Date(), nullable=False, comment="同步日期"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("order_code", "create_date", name="uq_order_code_date"),
    )
    op.create_index(
        "idx_daily_orders_customer_date",
        "daily_orders",
        ["customer_id", "create_date"],
        unique=False,
    )
    op.create_index("idx_daily_orders_sync_date", "daily_orders", ["sync_date"], unique=False)
    op.create_table(
        "daily_consumptions",
        sa.Column("customer_id", sa.Integer(), nullable=False, comment="客户 ID"),
        sa.Column("consumption_date", sa.Date(), nullable=False, comment="消费日期"),
        sa.Column("device_type", sa.String(length=50), nullable=False, comment="设备类型"),
        sa.Column("layer_type", sa.String(length=50), nullable=False, comment="图层类型"),
        sa.Column("order_count", sa.Integer(), nullable=True, comment="订单数量"),
        sa.Column(
            "total_cost", sa.Numeric(precision=12, scale=2), nullable=True, comment="总消费金额"
        ),
        sa.Column("pricing_rule_id", sa.Integer(), nullable=True, comment="定价规则 ID"),
        sa.Column("has_pricing_rule", sa.Boolean(), nullable=True, comment="是否有定价规则"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["pricing_rule_id"],
            ["pricing_rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "customer_id",
            "consumption_date",
            "device_type",
            "layer_type",
            name="uq_consumption_unique",
        ),
    )
    op.create_index(
        "idx_daily_consumption_customer_date",
        "daily_consumptions",
        ["customer_id", "consumption_date"],
        unique=False,
    )
    op.create_index(
        "idx_daily_consumption_date", "daily_consumptions", ["consumption_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_daily_consumption_date", table_name="daily_consumptions")
    op.drop_index("idx_daily_consumption_customer_date", table_name="daily_consumptions")
    op.drop_table("daily_consumptions")
    op.drop_index("idx_daily_orders_sync_date", table_name="daily_orders")
    op.drop_index("idx_daily_orders_customer_date", table_name="daily_orders")
    op.drop_table("daily_orders")
    # ### end Alembic commands ###
