"""add_sync_tasks_table

Revision ID: 59e4cca22335
Revises: 41b931a886e0
Create Date: 2026-06-24 15:13:04.962974

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers
revision: str = "59e4cca22335"
down_revision: Union[str, None] = "41b931a886e0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_tasks",
        sa.Column("id", sa.UUID(), nullable=False, comment="任务ID"),
        sa.Column("start_date", sa.Date(), nullable=False, comment="同步开始日期"),
        sa.Column("end_date", sa.Date(), nullable=False, comment="同步结束日期"),
        sa.Column("sync_mode", sa.String(length=20), nullable=False, comment="同步模式"),
        sa.Column("status", sa.String(length=20), nullable=False, comment="任务状态"),
        sa.Column("total_days", sa.Integer(), nullable=False, comment="总天数"),
        sa.Column(
            "completed_days", sa.Integer(), server_default="0", nullable=False, comment="已完成天数"
        ),
        sa.Column(
            "skipped_days", sa.Integer(), server_default="0", nullable=False, comment="跳过天数"
        ),
        sa.Column("current_date", sa.Date(), nullable=True, comment="当前处理日期"),
        sa.Column(
            "success_count",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="成功同步条数",
        ),
        sa.Column(
            "failed_count", sa.Integer(), server_default="0", nullable=False, comment="失败条数"
        ),
        sa.Column("error_message", sa.Text(), nullable=True, comment="失败原因"),
        sa.Column("operator_id", sa.Integer(), nullable=False, comment="操作人"),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True, comment="完成时间"),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["operator_id"], ["users.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_sync_tasks_status", "sync_tasks", ["status"], unique=False)
    op.create_index("idx_sync_tasks_operator", "sync_tasks", ["operator_id"], unique=False)
    op.create_index("idx_sync_tasks_created", "sync_tasks", ["created_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_sync_tasks_created", table_name="sync_tasks")
    op.drop_index("idx_sync_tasks_operator", table_name="sync_tasks")
    op.drop_index("idx_sync_tasks_status", table_name="sync_tasks")
    op.drop_table("sync_tasks")
    # ### end Alembic commands ###
