"""Add token_blacklist table

Revision ID: 734bdc29cc5e
Revises: 003
Create Date: 2026-04-08 00:15:47.813667

"""

from typing import Union, Sequence
from alembic import op
import sqlalchemy as sa


revision: str = "734bdc29cc5e"
down_revision: Union[str, None] = "003_files"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "token_blacklist",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("jti", sa.String(length=100), nullable=False),
        sa.Column("token_type", sa.String(length=20), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "blacklisted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_token_blacklist_expires", "token_blacklist", ["expires_at"], unique=False
    )
    op.create_index("idx_token_blacklist_jti", "token_blacklist", ["jti"], unique=False)
    op.create_index(
        op.f("ix_token_blacklist_jti"), "token_blacklist", ["jti"], unique=True
    )
    op.drop_index("ix_files_business_type", table_name="files")
    op.drop_index("ix_files_deleted_at", table_name="files")
    op.drop_index("ix_files_uploaded_by", table_name="files")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_files_uploaded_by", "files", ["uploaded_by"], unique=False)
    op.create_index("ix_files_deleted_at", "files", ["deleted_at"], unique=False)
    op.create_index("ix_files_business_type", "files", ["business_type"], unique=False)
    op.drop_index(op.f("ix_token_blacklist_jti"), table_name="token_blacklist")
    op.drop_index("idx_token_blacklist_jti", table_name="token_blacklist")
    op.drop_index("idx_token_blacklist_expires", table_name="token_blacklist")
    op.drop_table("token_blacklist")
    # ### end Alembic commands ###
