"""add_all_missing_tables

Revision ID: a5d21c5761aa
Revises: 002
Create Date: 2026-04-05 22:16:08.392789

"""

from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = "a5d21c5761aa"
down_revision: Union[str, None] = "002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sync_task_logs",
        sa.Column(
            "task_name", sa.String(length=100), nullable=False, comment="任务名称"
        ),
        sa.Column("status", sa.String(length=20), nullable=False, comment="任务状态"),
        sa.Column("total_count", sa.Integer(), nullable=True, comment="总处理数量"),
        sa.Column("success_count", sa.Integer(), nullable=True, comment="成功数量"),
        sa.Column("failed_count", sa.Integer(), nullable=True, comment="失败数量"),
        sa.Column("skipped_count", sa.Integer(), nullable=True, comment="跳过数量"),
        sa.Column(
            "executed_at", sa.String(length=50), nullable=True, comment="执行时间"
        ),
        sa.Column(
            "duration_seconds", sa.Integer(), nullable=True, comment="执行耗时 (秒)"
        ),
        sa.Column("error_message", sa.Text(), nullable=True, comment="错误信息"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sync_task_logs_task_name"),
        "sync_task_logs",
        ["task_name"],
        unique=False,
    )
    op.create_table(
        "webhook_signatures",
        sa.Column(
            "signature", sa.String(length=64), nullable=False, comment="请求签名"
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=False, comment="请求时间戳"),
        sa.Column(
            "endpoint", sa.String(length=100), nullable=False, comment="Webhook 端点"
        ),
        sa.Column("is_consumed", sa.Boolean(), nullable=True, comment="是否已使用"),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_webhook_sig_timestamp",
        "webhook_signatures",
        ["signature", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_signatures_signature"),
        "webhook_signatures",
        ["signature"],
        unique=True,
    )
    op.create_index(
        op.f("ix_webhook_signatures_timestamp"),
        "webhook_signatures",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "audit_logs",
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("module", sa.String(length=50), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=True),
        sa.Column("record_type", sa.String(length=50), nullable=True),
        sa.Column("changes", sa.JSON(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tags",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "type", name="uq_tags_name_type"),
    )
    op.create_index("idx_tag_type_category", "tags", ["type", "category"], unique=False)
    op.create_index(op.f("ix_tags_category"), "tags", ["category"], unique=False)
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=False)
    op.create_index(op.f("ix_tags_type"), "tags", ["type"], unique=False)
    op.create_table(
        "customer_balances",
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("total_amount", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("real_amount", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("bonus_amount", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("used_total", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("used_real", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("used_bonus", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("customer_id"),
    )
    op.create_table(
        "customer_profiles",
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("scale_level", sa.String(length=50), nullable=True),
        sa.Column("consume_level", sa.String(length=50), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("is_real_estate", sa.Boolean(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("customer_id"),
    )
    op.create_table(
        "customer_tags",
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["customer_id"], ["customers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("customer_id", "tag_id", "id"),
    )
    op.create_table(
        "daily_usage",
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("usage_date", sa.Date(), nullable=False),
        sa.Column("device_type", sa.String(length=20), nullable=False),
        sa.Column("layer_type", sa.String(length=20), nullable=True),
        sa.Column("quantity", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_daily_usage_customer_date",
        "daily_usage",
        ["customer_id", "usage_date"],
        unique=False,
    )
    op.create_index(
        "idx_daily_usage_customer_device",
        "daily_usage",
        ["customer_id", "device_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_daily_usage_customer_id"), "daily_usage", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_daily_usage_usage_date"), "daily_usage", ["usage_date"], unique=False
    )
    op.create_table(
        "invoices",
        sa.Column("invoice_no", sa.String(length=50), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("total_amount", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column("discount_amount", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("discount_reason", sa.Text(), nullable=True),
        sa.Column("discount_attachment", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("approver_id", sa.Integer(), nullable=True),
        sa.Column("approved_at", sa.String(length=50), nullable=True),
        sa.Column("customer_confirmed_at", sa.String(length=50), nullable=True),
        sa.Column("payment_proof", sa.String(length=255), nullable=True),
        sa.Column("paid_at", sa.String(length=50), nullable=True),
        sa.Column("completed_at", sa.String(length=50), nullable=True),
        sa.Column("is_auto_generated", sa.Boolean(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["approver_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_invoice_customer_period",
        "invoices",
        ["customer_id", "period_start", "period_end"],
        unique=False,
    )
    op.create_index(
        "idx_invoice_status_period",
        "invoices",
        ["status", "period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_invoices_customer_id"), "invoices", ["customer_id"], unique=False
    )
    op.create_index(
        op.f("ix_invoices_invoice_no"), "invoices", ["invoice_no"], unique=True
    )
    op.create_index(
        op.f("ix_invoices_period_end"), "invoices", ["period_end"], unique=False
    )
    op.create_index(
        op.f("ix_invoices_period_start"), "invoices", ["period_start"], unique=False
    )
    op.create_index(op.f("ix_invoices_status"), "invoices", ["status"], unique=False)
    op.create_table(
        "pricing_rules",
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("device_type", sa.String(length=20), nullable=False),
        sa.Column("pricing_type", sa.String(length=20), nullable=False),
        sa.Column("unit_price", sa.DECIMAL(precision=10, scale=2), nullable=True),
        sa.Column("tiers", sa.JSON(), nullable=True),
        sa.Column("package_type", sa.String(length=20), nullable=True),
        sa.Column("package_limits", sa.JSON(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_pricing_rules_customer_id"),
        "pricing_rules",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pricing_rules_effective_date"),
        "pricing_rules",
        ["effective_date"],
        unique=False,
    )
    op.create_table(
        "recharge_records",
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("real_amount", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column("bonus_amount", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("operator_id", sa.Integer(), nullable=True),
        sa.Column("payment_proof", sa.String(length=255), nullable=True),
        sa.Column("remark", sa.Text(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recharge_records_customer_id"),
        "recharge_records",
        ["customer_id"],
        unique=False,
    )
    op.create_table(
        "consumption_records",
        sa.Column("customer_id", sa.Integer(), nullable=True),
        sa.Column("invoice_id", sa.Integer(), nullable=True),
        sa.Column("amount", sa.DECIMAL(precision=12, scale=2), nullable=False),
        sa.Column("bonus_used", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("real_used", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("balance_after", sa.DECIMAL(precision=12, scale=2), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["invoice_id"],
            ["invoices.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_consumption_records_customer_id"),
        "consumption_records",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_consumption_records_invoice_id"),
        "consumption_records",
        ["invoice_id"],
        unique=False,
    )
    op.create_table(
        "invoice_items",
        sa.Column("invoice_id", sa.Integer(), nullable=True),
        sa.Column("device_type", sa.String(length=20), nullable=False),
        sa.Column("layer_type", sa.String(length=20), nullable=True),
        sa.Column("quantity", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("unit_price", sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column("pricing_rule_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["pricing_rule_id"],
            ["pricing_rules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_invoice_items_invoice_id"),
        "invoice_items",
        ["invoice_id"],
        unique=False,
    )
    op.create_table(
        "profile_tags",
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["profile_id"], ["customer_profiles.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("profile_id", "tag_id", "id"),
    )
    op.add_column(
        "customer_group_members",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    )
    op.drop_index(
        "idx_customer_group_members_customer_id", table_name="customer_group_members"
    )
    op.create_index(
        op.f("ix_customer_group_members_customer_id"),
        "customer_group_members",
        ["customer_id"],
        unique=False,
    )
    op.drop_index("idx_customer_groups_created_by", table_name="customer_groups")
    op.drop_index("idx_customer_groups_group_type", table_name="customer_groups")
    op.drop_index("idx_customer_groups_name", table_name="customer_groups")
    op.create_index(
        op.f("ix_customer_groups_created_by"),
        "customer_groups",
        ["created_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_groups_group_type"),
        "customer_groups",
        ["group_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customer_groups_name"), "customer_groups", ["name"], unique=False
    )
    op.create_index(
        "idx_customer_business_settlement",
        "customers",
        ["business_type", "settlement_type"],
        unique=False,
    )
    op.create_index(
        "idx_customer_manager_level",
        "customers",
        ["manager_id", "customer_level"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customers_account_type"), "customers", ["account_type"], unique=False
    )
    op.create_index(
        op.f("ix_customers_business_type"), "customers", ["business_type"], unique=False
    )
    op.create_index(
        op.f("ix_customers_customer_level"),
        "customers",
        ["customer_level"],
        unique=False,
    )
    op.create_index(op.f("ix_customers_email"), "customers", ["email"], unique=False)
    op.create_index(
        op.f("ix_customers_is_key_customer"),
        "customers",
        ["is_key_customer"],
        unique=False,
    )
    op.create_index(
        op.f("ix_customers_manager_id"), "customers", ["manager_id"], unique=False
    )
    op.create_index(
        op.f("ix_customers_settlement_type"),
        "customers",
        ["settlement_type"],
        unique=False,
    )
    op.create_foreign_key(None, "customers", "users", ["manager_id"], ["id"])
    op.drop_index("ix_permissions_code", table_name="permissions")
    op.create_unique_constraint(None, "permissions", ["code"])
    op.drop_index("ix_roles_name", table_name="roles")
    op.create_unique_constraint(None, "roles", ["name"])
    op.drop_index("ix_users_username", table_name="users")
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.create_index("ix_users_username", "users", ["username"], unique=True)
    op.drop_constraint(None, "roles", type_="unique")
    op.create_index("ix_roles_name", "roles", ["name"], unique=True)
    op.drop_constraint(None, "permissions", type_="unique")
    op.create_index("ix_permissions_code", "permissions", ["code"], unique=True)
    op.drop_constraint(None, "customers", type_="foreignkey")
    op.drop_index(op.f("ix_customers_settlement_type"), table_name="customers")
    op.drop_index(op.f("ix_customers_manager_id"), table_name="customers")
    op.drop_index(op.f("ix_customers_is_key_customer"), table_name="customers")
    op.drop_index(op.f("ix_customers_email"), table_name="customers")
    op.drop_index(op.f("ix_customers_customer_level"), table_name="customers")
    op.drop_index(op.f("ix_customers_business_type"), table_name="customers")
    op.drop_index(op.f("ix_customers_account_type"), table_name="customers")
    op.drop_index("idx_customer_manager_level", table_name="customers")
    op.drop_index("idx_customer_business_settlement", table_name="customers")
    op.drop_index(op.f("ix_customer_groups_name"), table_name="customer_groups")
    op.drop_index(op.f("ix_customer_groups_group_type"), table_name="customer_groups")
    op.drop_index(op.f("ix_customer_groups_created_by"), table_name="customer_groups")
    op.create_index(
        "idx_customer_groups_name", "customer_groups", ["name"], unique=False
    )
    op.create_index(
        "idx_customer_groups_group_type",
        "customer_groups",
        ["group_type"],
        unique=False,
    )
    op.create_index(
        "idx_customer_groups_created_by",
        "customer_groups",
        ["created_by"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_customer_group_members_customer_id"),
        table_name="customer_group_members",
    )
    op.create_index(
        "idx_customer_group_members_customer_id",
        "customer_group_members",
        ["customer_id"],
        unique=False,
    )
    op.drop_column("customer_group_members", "id")
    op.drop_table("profile_tags")
    op.drop_index(op.f("ix_invoice_items_invoice_id"), table_name="invoice_items")
    op.drop_table("invoice_items")
    op.drop_index(
        op.f("ix_consumption_records_invoice_id"), table_name="consumption_records"
    )
    op.drop_index(
        op.f("ix_consumption_records_customer_id"), table_name="consumption_records"
    )
    op.drop_table("consumption_records")
    op.drop_index(
        op.f("ix_recharge_records_customer_id"), table_name="recharge_records"
    )
    op.drop_table("recharge_records")
    op.drop_index(op.f("ix_pricing_rules_effective_date"), table_name="pricing_rules")
    op.drop_index(op.f("ix_pricing_rules_customer_id"), table_name="pricing_rules")
    op.drop_table("pricing_rules")
    op.drop_index(op.f("ix_invoices_status"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_period_start"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_period_end"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_invoice_no"), table_name="invoices")
    op.drop_index(op.f("ix_invoices_customer_id"), table_name="invoices")
    op.drop_index("idx_invoice_status_period", table_name="invoices")
    op.drop_index("idx_invoice_customer_period", table_name="invoices")
    op.drop_table("invoices")
    op.drop_index(op.f("ix_daily_usage_usage_date"), table_name="daily_usage")
    op.drop_index(op.f("ix_daily_usage_customer_id"), table_name="daily_usage")
    op.drop_index("idx_daily_usage_customer_device", table_name="daily_usage")
    op.drop_index("idx_daily_usage_customer_date", table_name="daily_usage")
    op.drop_table("daily_usage")
    op.drop_table("customer_tags")
    op.drop_table("customer_profiles")
    op.drop_table("customer_balances")
    op.drop_index(op.f("ix_tags_type"), table_name="tags")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_index(op.f("ix_tags_category"), table_name="tags")
    op.drop_index("idx_tag_type_category", table_name="tags")
    op.drop_table("tags")
    op.drop_table("audit_logs")
    op.drop_index(
        op.f("ix_webhook_signatures_timestamp"), table_name="webhook_signatures"
    )
    op.drop_index(
        op.f("ix_webhook_signatures_signature"), table_name="webhook_signatures"
    )
    op.drop_index("idx_webhook_sig_timestamp", table_name="webhook_signatures")
    op.drop_table("webhook_signatures")
    op.drop_index(op.f("ix_sync_task_logs_task_name"), table_name="sync_task_logs")
    op.drop_table("sync_task_logs")
    # ### end Alembic commands ###
