"""add cancelled_at to invoices

Revision ID: c09e8906c00d
Revises: 006_layer_type
Create Date: 2026-04-28 21:20:33.303484

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa

revision: str = 'c09e8906c00d'
down_revision: Union[str, None] = '006_layer_type'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('cancelled_at', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'cancelled_at')
    # ### end Alembic commands ###
