"""remove customer_level column from customers

Revision ID: dd4170648c62
Revises: dc8859579c78
Create Date: 2026-04-21 00:45:33.274860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from typing import Union, Sequence

revision: str = 'dd4170648c62'
down_revision: Union[str, None] = 'dc8859579c78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_token_blacklist_expires', table_name='token_blacklist')
    op.drop_index('idx_token_blacklist_jti', table_name='token_blacklist')
    op.drop_index('ix_token_blacklist_jti', table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_index('idx_customer_business_settlement', table_name='customers')
    op.drop_index('idx_customer_manager_level', table_name='customers')
    op.drop_index('ix_customers_business_type', table_name='customers')
    op.drop_index('ix_customers_customer_level', table_name='customers')
    op.drop_constraint('uq_customers_company_id', 'customers', type_='unique')
    op.create_index(op.f('ix_customers_cooperation_status'), 'customers', ['cooperation_status'], unique=False)
    op.create_index(op.f('ix_customers_is_disabled'), 'customers', ['is_disabled'], unique=False)
    op.create_index(op.f('ix_customers_sales_manager_id'), 'customers', ['sales_manager_id'], unique=False)
    op.drop_column('customers', 'business_type')
    op.drop_column('customers', 'customer_level')
    op.drop_constraint('industry_types_name_key', 'industry_types', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('industry_types_name_key', 'industry_types', ['name'])
    op.add_column('customers', sa.Column('customer_level', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('business_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_customers_sales_manager_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_is_disabled'), table_name='customers')
    op.drop_index(op.f('ix_customers_cooperation_status'), table_name='customers')
    op.create_unique_constraint('uq_customers_company_id', 'customers', ['company_id'])
    op.create_index('ix_customers_customer_level', 'customers', ['customer_level'], unique=False)
    op.create_index('ix_customers_business_type', 'customers', ['business_type'], unique=False)
    op.create_index('idx_customer_manager_level', 'customers', ['manager_id', 'customer_level'], unique=False)
    op.create_index('idx_customer_business_settlement', 'customers', ['business_type', 'settlement_type'], unique=False)
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('jti', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('token_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('blacklisted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='token_blacklist_pkey')
    )
    op.create_index('ix_token_blacklist_jti', 'token_blacklist', ['jti'], unique=True)
    op.create_index('idx_token_blacklist_jti', 'token_blacklist', ['jti'], unique=False)
    op.create_index('idx_token_blacklist_expires', 'token_blacklist', ['expires_at'], unique=False)
    # ### end Alembic commands ###
